-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 13:24:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_petsitting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_petsitting` ;

-- -----------------------------------------------------
-- Schema db_petsitting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_petsitting` DEFAULT CHARACTER SET utf8 ;
USE `db_petsitting` ;

-- -----------------------------------------------------
-- Table `db_petsitting`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsitting`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(125) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `role` ENUM('PARENT', 'SITTER', 'PARENTANDSITTER') NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `presentation` LONGTEXT NULL,
  `accomodation_type` ENUM('FLAT', 'HOUSE') NULL,
  `living_space` DECIMAL(4,2) NULL,
  `has_vehicule` TINYINT NULL,
  `has_garden` TINYINT NULL,
  `status` ENUM('AVAILABLE', 'NOTAVAILABLE', 'BANNED') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `db_petsitting`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsitting`.`animal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sex` ENUM('MALE', 'FEMALE') NOT NULL,
  `weight` DECIMAL(3,2) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `is_vaccinated` TINYINT NOT NULL,
  `is_sterilized` TINYINT NOT NULL,
  `pet_name` VARCHAR(45) NOT NULL,
  `breed` VARCHAR(45) NULL,
  `is_social` TINYINT NOT NULL,
  `pet_photo` VARCHAR(200) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_animal_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_animal_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_petsitting`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petsitting`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsitting`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `daily_price` DECIMAL(5,2) NOT NULL,
  `type` ENUM('WALK', 'VISIT', 'HOSTING') NOT NULL,
  `name` VARCHAR(125) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_service_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_petsitting`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petsitting`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsitting`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `total_price` DECIMAL(7,2) ZEROFILL NOT NULL,
  `animal_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_booking_animal1_idx` (`animal_id` ASC) VISIBLE,
  INDEX `fk_booking_service1_idx` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_animal1`
    FOREIGN KEY (`animal_id`)
    REFERENCES `db_petsitting`.`animal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `db_petsitting`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
